# Generated by Django 4.1.5 on 2023-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealie',
            name='carbohydrate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealie',
            name='fat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealie',
            name='protein',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
